//
//
//  Generated by Agora Plastic(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : C_obj.h
//  @ Date : 2005-08-18
//  @ Author : 
//
//


#if !defined(_C_OBJ_H)
#define _C_OBJ_H
#include "GameLobby.h"
#include <string.h>
#include <math.h>

#define MAP_OBJ_MOVE_VELOCITY 2

class C_obj {
public:	
	C_obj(char* nam, float mas,char* sha);
	/************************************************/
	/*	nam		:	오브젝트를 구분하기 위한 이름	*/
	/*	mas		:	질량							*/
	/*	sha		:	충돌체크를 위한 모양 구분		*/
	/************************************************/
	~C_obj();

	void crash_obj_move_up		( C_obj* temp );
	void crash_obj_move_down	( C_obj* temp );
	void crash_obj_move_left	( C_obj* temp );
	void crash_obj_move_right	( C_obj* temp );

	void crash_obj_fix_up		( C_obj* temp );
	void crash_obj_fix_down		( C_obj* temp );
	void crash_obj_fix_left		( C_obj* temp );
	void crash_obj_fix_right	( C_obj* temp );

	void	setedge			(int x, int y, int width, int height);
	void	setradius		(float ra);

	char*	getshafe		(							); //현재 불필요	
	char*	getname			(							); //오브젝트마다 주어진 이름 받아오기
	float	getmass			(							); //질량
	void	getxy			(	int* tx, int* ty		); //좌표 
	void	getvelocity		(	float* vx,  float* vy	); //속도 

	void	rename			(	char* name, char* rn	); //이름 수정

	void	setmass			(	float m					); //질량 수정
	void	setxy			(	int x,  int y			); //좌표 수정
	void	impulsex		(	float x					); //속도 변경
	void	impulsey		(	float y					); 

	void	moveto			(	int x, int y			); //맵 오브젝트의 이동될 좌표
	void	step_for_fixed	(							); //맵 오브젝트의 이동 연산
	virtual	void	step_for_movable();

	void	onDraw			(	HDC& hdc				); //그림을 뿌리자

	void	culision_with	(	C_obj* other_obj		); //다른 오브젝트와 충돌 체크

	void	setcolision_dir (	int dir					);
	int 	getcolision_dir (							);
	

	C_obj*	next;

	int			x, y;
	int			width;
	int			height;
	int			fbefore_state;
	int			mbefore_state;
private:
	
	char*		name;
	char*		shafe;

	float		radius;			//원은 추후에 추가...
	
	//int			edge[4][2];  /*다각형의 경우: 아직 미구현*/ //꼭지점을 txt에서 읽어오는 것도 괜찮을 듯

	int			index;

	C_obj*		fixed_info;
	
	float		surface;	//표면 마찰로 쓸거	
	float		mass;		//질량

	int			colision_direction;

	
	float		velocity_x;
	float		velocity_y;

	//맵 오브젝트 일 때
	int			n_pos_x;
	int			n_pos_y;

	
	void	setvelocity		(	float vx,float vy		); //속도 수정


};

#endif  //_C_OBJ_H
