//
//
//  Generated by Agora Plastic(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : C_physics.h
//  @ Date : 2005-08-18
//  @ Author : 
//
//


#if !defined(_C_PHYSICS_H)
#define _C_PHYSICS_H
#include "C_obj.h"
#include <math.h>

class C_physics {
public:
	//속성들;
	//리스트 관리;
	C_physics						( float gravx, float gravy );
	void	step					( /*HDC& hdc/*, DWORD time*/);
	void	setGravity				( float gravx, float gravy );
	void	movable_obj_include		( C_obj* inobj );
	void	fixed_obj_include		( C_obj* inobj );
	//서버로 부터의 패킷과 보유 패킷 비교
	void	check_next_position		( C_obj* temp );
	C_obj	evented_obj				();
	//리스트의 오브젝트 반환
	C_obj	ReturnObj				( char* name );
	//충돌 체크
	BOOL	culision_check			( C_obj* culision_main );
	//event 발생
	void	boom					( int x, int y, int width, int height, float power );
	//오브젝트 움직임
//	void	impulse					( char* name, float x, float y ) ;
	
private:
	float		Gravity[2];
	/****************************************************/
	/*					리스트 관련						*/
	/****************************************************/
	/*	draw	:	그림을 뿌리기 위한 리스트			*/
	/*	mavable	:	중력이 적용 되는 오브젝트 리스트	*/
	/*	fixed	:	고정된 물체 리스트					*/
	/****************************************************/
	C_obj*		draw_first;
	C_obj*		movable_first;
	C_obj*		fixed_first;
	C_obj*		movable_obj_list;
	C_obj*		fixed_obj_list;
	C_obj*		draw_obj_list;
	int			m_list_index;
	int			f_list_index;
};

#endif  //_C_PHYSICS_H
